### PR TITLE
fix: topNavigation styles

### LINKED ISSUE #1284: TopNavigation custom title with numberOfLines={1} renders wrong
## 🐛 Bug Report

When I use a custom **Text** component with **numberOfLines={1}** property in **title** of **TopNavigation** it gets clipped:

Screenshot 2020-11-05 at 19 22 06

## To Reproduce

```
<TopNavigation
  title={() => <Text numberOfLines={1}>VeryLongTextVeryLongTextVeryLongTextVeryLongTextVeryLongTextVeryLongTextVeryLongTextVeryLongText</Text>}
  accessoryLeft={BackAction}
/>
```
without **accessoryLeft** or **accessoryRight** properties set it works as expected:

Screenshot 2020-11-05 at 19 21 36

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |   2.0.0     |
| @ui-kitten/components   |   5.0.0      |

## Environment information

```bash

```

### PR DESCRIPTION
**Pull request by whitestranger7**
### Please read and mark the following check list before creating a pull request:

 - [x] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/react-native-ui-kitten/blob/master/CONTRIBUTING.md) guide.
 - [x] I read and followed the [New Feature Checklist](https://github.com/akveo/react-native-ui-kitten/blob/master/DEV_DOCS.md) guide.

 #### Short description of what this resolves:
Fixes #1284 by adding additional appropriate styles to containers.

### CODE REVIEW

File: src/components/ui/topNavigation/topNavigation.component.tsx [hunk 1]
```diff
@@ -158,7 +158,7 @@ export class TopNavigation extends React.Component<TopNavigationProps> {
         <View style={styles.leftControlContainer}>
           <FalsyFC component={accessoryLeft}/>
         </View>
-        <View style={alignmentStyles.titleContainer}>
+        <View style={[alignmentStyles.titleContainer, styles.titleContainer]}>
```
Comment (greenfrvr) [inline src/components/ui/topNavigation/topNavigation.component.tsx:161]: @whitestranger7 consider using `||` operator, instead of merging to style objects. The idea here is that we want to apply one of 2 styles at a time according to our use case, but in alignment 'center' case they will be merged.

**Review by malashkevich — APPROVED** [review]
