### PR TITLE
fix: menu onPress event for groups & items

### LINKED ISSUE #1207: MenuGroup onPress is never fired
## 🐛 Bug Report

When using `MenuGroups`,  any `TouchableOpacityProps` were supposed to be accepted, but if you pass `onPress` it will never be fired because it will be overridden in the `render` function.

TouchableOpacityProps reference
https://github.com/akveo/react-native-ui-kitten/blob/ea4a3620e78a262419ee6c5b116dc70a5645eefd/src/components/ui/menu/menuGroup.component.tsx#L59

Render reference
https://github.com/akveo/react-native-ui-kitten/blob/ea4a3620e78a262419ee6c5b116dc70a5645eefd/src/components/ui/menu/menuGroup.component.tsx#L175

## To Reproduce

1. Create a Menu and add a `MenuGroup` item
2. Add the `TouchableOpacityProps` 
  ```javascript
<Menu>
   <MenuGroup
       onPressIn={() => console.log("onPressIn")}
       onPress={() => console.log("onPress")}
       onPressOut={() => console.log("onPressOut")}>
   // ...
```

## Expected behavior

When you tap on the `MenuGroup` item we expected to see the following in the console
```bash
onPressIn
onPress
onPressOut
```

But you only see
```bash
onPressIn
onPressOut
```

## Link to runnable example or repository (highly encouraged)

https://snack.expo.io/3JHB_ESV6

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |     2.0.0   |
| @ui-kitten/components   |     5.0.0    |

## Environment information

```bash
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.3, 30.0.1
      System Images: android-30 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
```

### PR DESCRIPTION
**Pull request by whitestranger7**
### Please read and mark the following check list before creating a pull request:

 - [x] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/react-native-ui-kitten/blob/master/CONTRIBUTING.md) guide.
 - [x] I read and followed the [New Feature Checklist](https://github.com/akveo/react-native-ui-kitten/blob/master/DEV_DOCS.md) guide.

 #### Short description of what this resolves:
Fix for menu onPress event

Closes #1207

### CODE REVIEW

File: src/components/ui/menu/menuItem.component.tsx [hunk 1]
```diff
@@ -36,7 +36,7 @@ type MenuItemStyledProps = Overwrite<StyledComponentProps, {
 }>;
 
 type TouchableMenuItemProps = Overwrite<TouchableWebProps, {
-  onPress?: (descriptor: MenuItemDescriptor, event?: GestureResponderEvent) => void;
+  onPress?: () => void;
```
Comment (artyorsh) [inline src/components/ui/menu/menuItem.component.tsx:39]:
```suggestion
  onPress?: (event: GestureResponderEvent, descriptor: MenuItemDescriptor) => void;
```

File: src/components/ui/menu/menu.component.tsx [hunk 2]
```diff
@@ -149,7 +149,7 @@ export class Menu extends React.Component<MenuProps> {
     const descriptor = this.service.createDescriptorForElement(info.item, info.index);
     const selected: boolean = this.isItemSelected(descriptor);
 
-    return this.cloneItemWithProps(info.item, { descriptor, selected, onPress: this.onItemPress });
+    return this.cloneItemWithProps(info.item, { descriptor, selected, onItemPress: this.onItemPress });
```
Comment (artyorsh) [inline src/components/ui/menu/menu.component.tsx:152]: Instead of defining a special prop for that, I would suggest leaving only onPress, but with the following structure:

`onPress: (event, descriptor)`

This way we save the original React way of handling press events by leaving event object as first argument passed to handler function. But we still able to use internal implementation (descriptor) as a second argument.

```
private renderItem = (info: ListRenderItemInfo<MenuItemElement>): React.ReactElement => {
    const descriptor = this.service.createDescriptorForElement(info.item, info.index);

    return this.cloneItemWithProps(info.item, {
      descriptor: descriptor,
      selected: this.isItemSelected(descriptor),
      onPress: (event: GestureResponderEvent): void => {
        info.item.props.onPress && info.item.props.onPress(event, descriptor);
        this.onItemPress(descriptor);
      },
    });
  };
```

File: src/components/ui/menu/menuItem.component.tsx [hunk 3]
```diff
@@ -45,6 +45,7 @@ export interface MenuItemProps extends TouchableMenuItemProps, MenuItemStyledPro
   accessoryRight?: RenderProp<Partial<ImageProps>>;
   selected?: boolean;
   descriptor?: MenuItemDescriptor;
+  onItemPress?: (descriptor: MenuItemDescriptor, event?: GestureResponderEvent) => void;
```
Comment (artyorsh) [inline src/components/ui/menu/menuItem.component.tsx:48]:
```suggestion
```

File: src/components/ui/menu/menuItem.component.tsx [hunk 4]
```diff
@@ -95,7 +96,8 @@ export class MenuItem extends React.Component<MenuItemProps> {
   };
 
   private onPress = (event: GestureResponderEvent): void => {
-    this.props.onPress && this.props.onPress(this.props.descriptor, event);
+    this.props.onPress && this.props.onPress();
+    this.props.onItemPress && this.props.onItemPress(this.props.descriptor, event);
```
Comment (artyorsh) [inline src/components/ui/menu/menuItem.component.tsx:100]:
```suggestion
    this.props.onPress && this.props.onPress(event, this.props.descriptor);
```

**Review by artyorsh — CHANGES_REQUESTED** [review]

File: src/components/ui/menu/menu.component.tsx [hunk 5]
```diff
@@ -127,6 +127,7 @@ export class Menu extends React.Component<MenuProps> {
   };
 
   private onItemPress = (descriptor: MenuItemDescriptor): void => {
+    console.log('press');
```
Comment (artyorsh) [inline src/components/ui/menu/menu.component.tsx:130]:
```suggestion
```

**Review by artyorsh — COMMENTED** [review]
Please get rig of console logs 👍

**Review by malashkevich — APPROVED** [review]

**Comment by malashkevich** [comment]
@whitestranger7 tests are failing

File: src/components/ui/menu/menu.spec.tsx [hunk 6]
```diff
@@ -182,12 +184,49 @@ describe('@menu: component checks', () => {
   });
 
   it('should fire onPress event for group & item separately', () => {
+    const onFirstSelect = jest.fn((index: IndexPath) => {
```
Comment (malashkevich) [inline src/components/ui/menu/menu.spec.tsx:187]: it should be 2 tests, not one

**Review by artyorsh — APPROVED** [review]
