### PR TITLE
update rn, fix eslint, ts errors

### LINKED ISSUE #1640: Support React Version 18 and React Native 0.69 (latest), especially in conjunction with expo SDK 46.
Hello,

I was wondering when this library will support later versions for React and React Native and what the update timeline for this is.
Looking at the package.json (https://github.com/akveo/react-native-ui-kitten/blob/master/package.json) I see the following versions being enforced:

```
    "react": "~16.9.0",
    "react-native": "~0.61.4",
    "react-native-svg": "~9.13.6",
    "react-native-testing-library": "^1.12.0",
    "react-test-renderer": "16.9.0",
```

Are there any known issues using this library with React v18 and React Native 0.69, especially with the widely used expo environment for react native https://github.com/expo/expo.

Thank you for a quick response.

Thumbs up if any of you have the similar question.

### PR DESCRIPTION
**Pull request by AndreiPirovich**
### Please read and mark the following check list before creating a pull request:

 - [] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/react-native-ui-kitten/blob/master/CONTRIBUTING.md) guide.
 - [] I read and followed the [New Feature Checklist](https://github.com/akveo/react-native-ui-kitten/blob/master/DEV_DOCS.md) guide.

 #### Short description of what this resolves:
updated react-native to 0.69.5, fixed eslint, ts errors

### CODE REVIEW

File: src/components/devsupport/services/rtl/rtlFlexMap.ts [hunk 1]
```diff
@@ -71,6 +71,7 @@ const FlexWrapMapper: RTLFlexMapper<string> = {
 /**
  * Matches FlexBox style properties that can affect on Layout depending on LTR/RTL mode corresponding Mappers
  */
+// eslint-disable-next-line @typescript-eslint/no-explicit-any
 export const RtlFlexMap: Record<string, RTLFlexMapper<any>> = {
```
Comment (greenfrvr) [inline src/components/devsupport/services/rtl/rtlFlexMap.ts:75]: Currently `RTLFlexMapper` use only `string` as type parameter. I think for now we can declare `string` as a generic parameter. If in future we will add some number or boolean transforms we can add corresponding type explicitly (e.g. `string` | `number`). I think we can easily avoid `any` here.

File: src/components/devsupport/components/measure/measure.component.tsx [hunk 2]
```diff
@@ -11,16 +11,17 @@ import {
   StatusBar,
 } from 'react-native';
 import { Frame } from './type';
- 
+
+// eslint-disable-next-line @typescript-eslint/no-explicit-any
 export interface MeasureElementProps<P = any> {
```
Comment (greenfrvr) [inline src/components/devsupport/components/measure/measure.component.tsx:16]: It seems generic here may be omitted.

File: src/components/devsupport/typings.ts [hunk 3]
```diff
@@ -1,12 +1,14 @@
 import { ReactElement } from 'react';
 
 export type ChildrenProp<Element extends ReactElement = ReactElement> = Element | Element[];
+// eslint-disable-next-line @typescript-eslint/ban-types
 export type ChildrenWithProps<Props = {}> = ChildrenProp<ReactElement<Props>>;
```
Comment (greenfrvr) [inline src/components/devsupport/typings.ts:5]: We can get rid of default type value (as we did [here](src/components/devsupport/components/falsyFC/falsyFC.component.tsx) for example)

File: src/components/ui/autocomplete/autocomplete.spec.tsx [hunk 4]
```diff
@@ -48,41 +47,52 @@ jest.mock('react-native', () => {
 
 describe('@autocomplete-item: component checks', () => {
 
-  const TestAutocompleteItem = (props?: AutocompleteItemProps) => (
+  const TestAutocompleteItem = (props?: AutocompleteItemProps): JSX.Element => (
```
Comment (greenfrvr) [inline src/components/ui/autocomplete/autocomplete.spec.tsx:50]: all specs return `JSX.Element`, but in the rest code we use `React.ReactElement`. does it make sense to make return type consistent?

File: src/components/ui/shared/tabIndicator.component.tsx [hunk 5]
```diff
@@ -73,19 +73,21 @@ export class TabIndicator extends React.Component<TabIndicatorProps> {
...
    * }
    */
-  public scrollToOffset(params: { offset: number, animated?: boolean }) {
+  public scrollToOffset(params: { offset: number; animated?: boolean }): void {
     this.createOffsetAnimation(params).start(this.onContentOffsetAnimationStateEnd);
   }
 
-  private onContentOffsetAnimationStateChanged = (state: { value: number }) => {
+  // eslint-disable-next-line @typescript-eslint/no-unused-vars
+  private onContentOffsetAnimationStateChanged = (state: { value: number }): void => {
```
Comment (greenfrvr) [inline src/components/ui/shared/tabIndicator.component.tsx:81]: it seems we don't need those 2 methods as they do nothing

File: src/showcases/components/button/buttonAccessories.component.tsx [hunk 6]
```diff
@@ -1,33 +1,61 @@
...
-  <Icon {...props} name='star'/>
+const StarIcon = (props): IconElement => (
+  <Icon
+    {...props}
+    name='star'
+  />
 );
 
-const LoadingIndicator = (props) => (
+const LoadingIndicator = (props): React.ReactElement => (
```
Comment (greenfrvr) [inline src/showcases/components/button/buttonAccessories.component.tsx:12]: we won't need disable lint if we declare props to be `ImageProps`

File: src/showcases/components/button/buttonSimpleUsage.component.tsx [hunk 7]
```diff
@@ -2,19 +2,26 @@ import React from 'react';
...
+      level='1'
+    >
 
       <Button onPress={() => setCounter(counter + 1)}>
         BUTTON
       </Button>
 
       <Text style={styles.text}>
-        Pressed {counter} times
+        Pressed
```
Comment (greenfrvr) [inline src/showcases/components/button/buttonSimpleUsage.component.tsx:20]: isn't it better to use string interpolation here?

File: src/showcases/components/button/buttonTheming.component.tsx [hunk 8]
```diff
@@ -1,33 +1,61 @@
...
-  <Icon {...props} name='star'/>
+const StarIcon = (props): IconElement => (
+  <Icon
+    {...props}
+    name='star'
+  />
 );
 
-const LoadingIndicator = (props) => (
+const LoadingIndicator = (props): React.ReactElement => (
```
Comment (greenfrvr) [inline src/showcases/components/button/buttonTheming.component.tsx:12]: the same here, declaring props as `ImageProps` will let to get rid of lint disabling

File: src/showcases/components/calendar/calendarInitialVisibleDate.component.tsx [hunk 9]
```diff
@@ -6,41 +6,52 @@ const now = new Date();
...
 
       <View style={styles.calendarContainer}>
         <Text
           category='h6'
-          style={styles.text}>
-          Selected date: {selectedDate.toLocaleDateString()}
+          style={styles.text}
+        >
+          Selected date:
+          {' '}
```
Comment (greenfrvr) [inline src/showcases/components/calendar/calendarInitialVisibleDate.component.tsx:45]: consider using string interpolation

File: src/showcases/components/calendar/calendarSimpleUsage.component.tsx [hunk 10]
```diff
@@ -1,22 +1,22 @@
...
   const [date, setDate] = React.useState(new Date());
 
   return (
-    <React.Fragment>
-
+    <>
       <Text category='h6'>
-        Selected date: {date.toLocaleDateString()}
+        Selected date:
+        {' '}
```
Comment (greenfrvr) [inline src/showcases/components/calendar/calendarSimpleUsage.component.tsx:12]: consider using string interpolation

File: src/showcases/components/card/cardAccessories.component.tsx [hunk 11]
```diff
@@ -2,52 +2,79 @@ import React from 'react';
 import { StyleSheet, View } from 'react-native';
 import { Button, Card, Layout, Text } from '@ui-kitten/components';
 
-const Header = (props) => (
+const Header = (props): React.ReactElement => (
```
Comment (greenfrvr) [inline src/showcases/components/card/cardAccessories.component.tsx:5]: we can declare props as `ViewProps` here

File: src/showcases/components/datepicker/datepickerSimpleUsage.component.tsx [hunk 12]
```diff
@@ -2,15 +2,20 @@ import React from 'react';
...
-    <Layout style={styles.container} level='1'>
+    <Layout
+      style={styles.container}
+      level='1'
+    >
 
       <Text category='h6'>
-        Selected date: {date.toLocaleDateString()}
+        Selected date:
+        {' '}
```
Comment (greenfrvr) [inline src/showcases/components/datepicker/datepickerSimpleUsage.component.tsx:17]: consider using string interpolation

File: src/showcases/components/datepicker/datepickerTheming.component.tsx [hunk 13]
```diff
@@ -2,15 +2,20 @@ import React from 'react';
...
-    <Layout style={styles.container} level='1'>
+    <Layout
+      style={styles.container}
+      level='1'
+    >
 
       <Text category='h6'>
-        Selected date: {date.toLocaleDateString()}
+        Selected date:
+        {' '}
```
Comment (greenfrvr) [inline src/showcases/components/datepicker/datepickerTheming.component.tsx:17]: consider using string interpolation

File: src/showcases/components/drawer/drawerAccessories.component.tsx [hunk 14]
```diff
@@ -1,38 +1,49 @@
...
+const ForwardIcon = (props): IconElement => (
+  <Icon
+    {...props}
+    name='arrow-ios-forward'
+  />
 );
 
-const Header = (props) => (
-  <React.Fragment>
+const Header = (props): React.ReactElement => (
```
Comment (greenfrvr) [inline src/showcases/components/drawer/drawerAccessories.component.tsx:26]: props can be declared as `ViewProps`

File: src/showcases/components/list/listItemSimpleUsage.component.tsx [hunk 15]
```diff
@@ -1,21 +1,22 @@
...
 
-const InstallButton = (props) => (
+const InstallButton = (): React.ReactElement => (
   <Button size='tiny'>
     INSTALL
   </Button>
 );
 
-const ItemImage = (props) => (
+const ItemImage = (props): React.ReactElement => (
```
Comment (greenfrvr) [inline src/showcases/components/list/listItemSimpleUsage.component.tsx:10]: props can be declared as `ImageProps` here

File: src/showcases/components/topNavigation/topNavigationSimpleUsage.component.tsx [hunk 16]
```diff
@@ -1,25 +1,37 @@
...
   <TopNavigation
     accessoryLeft={BackAction}
     title='Eva Application'
   />
 );
 
 
-const TopNavigationStyling = () => (
+// eslint-disable-next-line @typescript-eslint/no-unused-vars
+const TopNavigationStyling = (): React.ReactElement => (
```
Comment (greenfrvr) [inline src/showcases/components/topNavigation/topNavigationSimpleUsage.component.tsx:24]: do we still need thing component?

File: src/showcases/components/styled/styledComponentVariants.component.tsx [hunk 17]
```diff
@@ -1,23 +1,27 @@
 import React from 'react';
 import { TouchableOpacity } from 'react-native';
-import { Interaction, styled } from '@ui-kitten/components';
+import { EvaProp, Interaction, styled } from '@ui-kitten/components';
+
+interface IProps {
```
Comment (greenfrvr) [inline src/showcases/components/styled/styledComponentVariants.component.tsx:5]: Please rename non-exportable interface to `Props`. According to our styleguide we avoid `I` prefixes

**Review by greenfrvr — APPROVED** [review]
