### PR TITLE
Fix: update popover render implementation

### LINKED ISSUE #1471: Popover wrong behaviour with FalsyFC realisation
## 🐛 Bug Report

The bug seems to be appeared after #1462 , right after FalsyFC realisation was [implemented into Popover anchor render](https://github.com/akveo/react-native-ui-kitten/blob/a985f079d062dbf70195e0a06f6ab0044c3caf65/src/components/ui/popover/popover.component.tsx#L236). With FalseFC realisation - Popover blocks on first render on position (0, 0 ,0 ,0) and then block [`measureSelf()`](https://github.com/akveo/react-native-ui-kitten/blob/a985f079d062dbf70195e0a06f6ab0044c3caf65/src/components/devsupport/components/measure/measure.component.tsx#L67) in order to rerender on appropriate position. It's starts working without block from second render after initialized.

Looks like FalsyFC return [`createElement()`](https://github.com/akveo/react-native-ui-kitten/blob/a985f079d062dbf70195e0a06f6ab0044c3caf65/src/components/devsupport/components/falsyFC/falsyFC.component.tsx#L52) somehow apply `onMeasure` prop with initialized (0, 0, 0, 0) values.

## To Reproduce

Implement straightforward Popover realisation from this example https://akveo.github.io/react-native-ui-kitten/docs/assets/playground-build/#/PopoverSimpleUsage. Make sure you're using current react-native-ui-kitten packages from [`master`](https://github.com/akveo/react-native-ui-kitten/tree/master) branch.

First popover render call will brings Popover on (0, 0, 0, 0) screen position.

## Expected behavior

Popover appears on appropriate position on first render call.
## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva     | 5.1.0       |
| @ui-kitten/components   | 5.1.0        |

## Environment information

```bash
System:
    OS: macOS 11.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.14.0 - ~/.nvm/versions/node/v14.15.4/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-23 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7322048
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.13.1 => 16.13.1 
    react-native: ~0.63.4 => 0.63.4 
```

### PR DESCRIPTION
**Pull request by whitestranger7**
### Please read and mark the following check list before creating a pull request:

 - [x] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/react-native-ui-kitten/blob/master/CONTRIBUTING.md) guide.
 - [x] I read and followed the [New Feature Checklist](https://github.com/akveo/react-native-ui-kitten/blob/master/DEV_DOCS.md) guide.

 #### Short description of what this resolves:

- Resolves issue with Select component
- Roll back Popover changes from #1462

### CODE REVIEW

File: src/components/ui/popover/popover.component.tsx [hunk 1]
```diff
@@ -222,18 +222,22 @@ export class Popover extends React.Component<PopoverProps, State> {
...
-        {this.renderPopoverElement()}
+        <FalsyFC component={this.renderPopoverElement()} />
       </MeasureElement>
     );
   };
 
   public render(): React.ReactElement {
+    const renderAnchor = typeof this.props.anchor === 'function' 
+      ? this.props.anchor() 
+      : this.props.anchor
```
Comment (artyorsh) [inline src/components/ui/popover/popover.component.tsx:233]: Naaaah, can we get rid of this? The RenderProp does the same check actually. I believe there is a proper way to solve it

**Review by malashkevich — APPROVED** [review]
